### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method on a null object reference

### ISSUE THREAD

**Issue by alidhkh** [crazecoder/open_file#110]
Hi, this is my file path:
`
/data/user/0/myapp/app_flutter/IMG.jpg
`
I receive this error:
```
E/MethodChannel#open_file(20780): Failed to handle method call
E/MethodChannel#open_file(20780): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
E/MethodChannel#open_file(20780): 	at com.crazecoder.openfile.OpenFilePlugin.getFileType(OpenFilePlugin.java:168)
E/MethodChannel#open_file(20780): 	at com.crazecoder.openfile.OpenFilePlugin.onMethodCall(OpenFilePlugin.java:94)
E/MethodChannel#open_file(20780): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#open_file(20780): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#open_file(20780): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/MethodChannel#open_file(20780): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#open_file(20780): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/MethodChannel#open_file(20780): 	at android.os.Looper.loop(Looper.java:136)
E/MethodChannel#open_file(20780): 	at android.app.ActivityThread.main(ActivityThread.java:6077)
E/MethodChannel#open_file(20780): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#open_file(20780): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
E/MethodChannel#open_file(20780): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
E/flutter (20780): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
E/flutter (20780): 	at com.crazecoder.openfile.OpenFilePlugin.getFileType(OpenFilePlugin.java:168)
E/flutter (20780): 	at com.crazecoder.openfile.OpenFilePlugin.onMethodCall(OpenFilePlugin.java:94)
E/flutter (20780): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter (20780): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter (20780): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/flutter (20780): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (20780): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/flutter (20780): 	at android.os.Looper.loop(Looper.java:136)
E/flutter (20780): 	at android.app.ActivityThread.main(ActivityThread.java:6077)
E/flutter (20780): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (20780): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
E/flutter (20780): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
E/flutter (20780): )
E/flutter (20780): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582:7)
E/flutter (20780): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:18)
E/flutter (20780): <asynchronous suspension>
E/flutter (20780): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter (20780): #3      OpenFile.open (package:open_file/src/plaform/open_file.dart:34:36)
E/flutter (20780): #4      Hello._widget.<anonymous closure>.<anonymous closure> (package:myapp/data/conversations.dart:75:28)
E/flutter (20780): #5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:993:19)
E/flutter (20780): #6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1111:38)
E/flutter (20780): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
E/flutter (20780): #8      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
E/flutter (20780): #9      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
E/flutter (20780): #10     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:259:7)
E/flutter (20780): #11     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157:27)
E/flutter (20780): #12     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:362:20)
E/flutter (20780): #13     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338:22)
E/flutter (20780): #14     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267:11)
E/flutter (20780): #15     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:295:7)
E/flutter (20780): #16     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240:7)
E/flutter (20780): #17     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213:7)
E/flutter (20780): #18     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter (20780): #19     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (20780): #20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (20780): #21     _invoke1 (dart:ui/hooks.dart:265:10)
E/flutter (20780): #22     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
E/flutter (20780): 
```

**Comment by alidhkh** [comment]
Passing a previously saved string path to open function wasn't working. I used these functions mentioned in another issue.

```
Future<String> get _localPath async {
  final directory = await getApplicationDocumentsDirectory();

  return directory.path;
}

Future<File> _localFile(String fileName) async {
  final path = await _localPath;
  return File('$path$fileName');
}

var file = await _localFile(tile.fileName);
OpenFile.open(file.path);
```
