### ISSUE TITLE
total crash when 'No Activity found'

### ISSUE THREAD

**Issue by szotp** [crazecoder/open_file#12]
App gets killed when I try to open docx file. Would it make sense to just add try/catch for `startActivityForResult` to prevent that?

```
E/MethodChannel#open_file(21430): android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW cat=[android.intent.category.DEFAULT] dat=content://com.example.xxx.fileProvider/cache-path/Word.docx typ=application/vnd.openxmlformats-officedocument.wordprocessingml.document flg=0x20000001 }
E/MethodChannel#open_file(21430): 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2007)
E/MethodChannel#open_file(21430): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1673)
E/MethodChannel#open_file(21430): 	at android.app.Activity.startActivityForResult(Activity.java:4586)
E/MethodChannel#open_file(21430): 	at android.app.Activity.startActivityForResult(Activity.java:4544)
E/MethodChannel#open_file(21430): 	at com.crazecoder.openfile.OpenFilePlugin.onMethodCall(OpenFilePlugin.java:65)
E/MethodChannel#open_file(21430): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:191)
E/MethodChannel#open_file(21430): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
E/MethodChannel#open_file(21430): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#open_file(21430): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#open_file(21430): 	at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#open_file(21430): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/MethodChannel#open_file(21430): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#open_file(21430): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#open_file(21430): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by daryll-fourie** [comment]
Any feedback on this issue? I'm also getting the app crash when trying to open a file type which isn't supported. This should be a quick fix? The `try-catch` should work?

**Comment by daryll-fourie** [comment]
@crazecoder any feedback regarding this issue?

**Comment by crazecoder** [comment]
fixed,try it
