### ISSUE TITLE
安卓5.1.1出现问题

### ISSUE THREAD

**Issue by lan2000** [crazecoder/open_file#128]
日志：
/com.cyanogenmod.filemanager E/EditorActivity: Failed to get file reference
    com.cyanogenmod.filemanager.console.InsufficientPermissionsException
        at com.cyanogenmod.filemanager.commands.shell.Shell.checkStdErr(Shell.java:128)
        at com.cyanogenmod.filemanager.console.shell.ShellConsole.syncExecute(ShellConsole.java:721)
        at com.cyanogenmod.filemanager.console.shell.ShellConsole.execute(ShellConsole.java:541)
        at com.cyanogenmod.filemanager.console.shell.ShellConsole.execute(ShellConsole.java:486)
        at com.cyanogenmod.filemanager.util.CommandHelper.execute(CommandHelper.java:1908)
        at com.cyanogenmod.filemanager.util.CommandHelper.getFileInfo(CommandHelper.java:578)
        at com.cyanogenmod.filemanager.activities.EditorActivity.readFile(EditorActivity.java:1023)
        at com.cyanogenmod.filemanager.activities.EditorActivity.onCreate(EditorActivity.java:633)
        at android.app.Activity.performCreate(Activity.java:5990)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
        at android.app.ActivityThread.access$800(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)

/com.cyanogenmod.filemanager E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.cyanogenmod.filemanager, PID: 9326
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.cyanogenmod.filemanager/com.cyanogenmod.filemanager.activities.EditorActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'long com.cyanogenmod.filemanager.model.FileSystemObject.getSize()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
        at android.app.ActivityThread.access$800(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'long com.cyanogenmod.filemanager.model.FileSystemObject.getSize()' on a null object reference
        at com.cyanogenmod.filemanager.activities.EditorActivity.readFile(EditorActivity.java:1031)
        at com.cyanogenmod.filemanager.activities.EditorActivity.onCreate(EditorActivity.java:633)
        at android.app.Activity.performCreate(Activity.java:5990)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
        at android.app.ActivityThread.access$800(ActivityThread.java:151) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5254) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)

**Comment by lan2000** [comment]
I/PackageManager: Setting last chosen activity com.cyanogenmod.filemanager/.activities.EditorActivity for user 0:
/system_process I/PackageManager:   Action: "android.intent.action.VIEW"
system_process I/PackageManager:   Category: "android.intent.category.DEFAULT"
/system_process I/PackageManager:   Type: "text/plain"
system_process I/ActivityManager: START u0 {act=android.intent.action.VIEW cat=[android.intent.category.DEFAULT] dat=file:///data/data/包名/cache/file_picker/873585f7-2c20-53fb-810a-9ff98765a23f.txt typ=text/plain flg=0x23000000 cmp=com.cyanogenmod.filemanager/.activities.EditorActivity} from uid 10033 on display 0
D/ld_audio_hw: ld_start_output_stream, stream=0xb604a660, sampleRate=44100, channel=2, bps=16, bufSize=2048

**Comment by lan2000** [comment]
> 日志：
> /com.cyanogenmod.filemanager E/EditorActivity: Failed to get file reference
> com.cyanogenmod.filemanager.console.InsufficientPermissionsException
> at com.cyanogenmod.filemanager.commands.shell.Shell.checkStdErr(Shell.java:128)
> at com.cyanogenmod.filemanager.console.shell.ShellConsole.syncExecute(ShellConsole.java:721)
> at com.cyanogenmod.filemanager.console.shell.ShellConsole.execute(ShellConsole.java:541)
> at com.cyanogenmod.filemanager.console.shell.ShellConsole.execute(ShellConsole.java:486)
> at com.cyanogenmod.filemanager.util.CommandHelper.execute(CommandHelper.java:1908)
> at com.cyanogenmod.filemanager.util.CommandHelper.getFileInfo(CommandHelper.java:578)
> at com.cyanogenmod.filemanager.activities.EditorActivity.readFile(EditorActivity.java:1023)
> at com.cyanogenmod.filemanager.activities.EditorActivity.onCreate(EditorActivity.java:633)
> at android.app.Activity.performCreate(Activity.java:5990)
> at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
> at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
> at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
> at android.app.ActivityThread.access$800(ActivityThread.java:151)
> at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
> at android.os.Handler.dispatchMessage(Handler.java:102)
> at android.os.Looper.loop(Looper.java:135)
> at android.app.ActivityThread.main(ActivityThread.java:5254)
> at java.lang.reflect.Method.invoke(Native Method)
> at java.lang.reflect.Method.invoke(Method.java:372)
> at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
> 
> /com.cyanogenmod.filemanager E/AndroidRuntime: FATAL EXCEPTION: main
> Process: com.cyanogenmod.filemanager, PID: 9326
> java.lang.RuntimeException: Unable to start activity ComponentInfo{com.cyanogenmod.filemanager/com.cyanogenmod.filemanager.activities.EditorActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'long com.cyanogenmod.filemanager.model.FileSystemObject.getSize()' on a null object reference
> at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
> at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
> at android.app.ActivityThread.access$800(ActivityThread.java:151)
> at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
> at android.os.Handler.dispatchMessage(Handler.java:102)
> at android.os.Looper.loop(Looper.java:135)
> at android.app.ActivityThread.main(ActivityThread.java:5254)
> at java.lang.reflect.Method.invoke(Native Method)
> at java.lang.reflect.Method.invoke(Method.java:372)
> at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
> Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'long com.cyanogenmod.filemanager.model.FileSystemObject.getSize()' on a null object reference
> at com.cyanogenmod.filemanager.activities.EditorActivity.readFile(EditorActivity.java:1031)
> at com.cyanogenmod.filemanager.activities.EditorActivity.onCreate(EditorActivity.java:633)
> at android.app.Activity.performCreate(Activity.java:5990)
> at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
> at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
> at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
> at android.app.ActivityThread.access$800(ActivityThread.java:151) 
> at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
> at android.os.Handler.dispatchMessage(Handler.java:102) 
> at android.os.Looper.loop(Looper.java:135) 
> at android.app.ActivityThread.main(ActivityThread.java:5254) 
> at java.lang.reflect.Method.invoke(Native Method) 
> at java.lang.reflect.Method.invoke(Method.java:372) 
> at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905) 
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
