### ISSUE TITLE
安卓5.1.1，打开内部存储文件（/data/data/包名/cache/file_pickerr/xxx.jpg）出现错误

### ISSUE THREAD

**Issue by lan2000** [crazecoder/open_file#129]
但是安卓5.1.1打开外部存储路径文件没问题，
比如路径/storage/emulated/0/Android/data/包名/cache/text/xxx.txt

我测试另外一台安卓10的手机，能正常打开内部存储文件（/data/data/包名/cache/file_pickerr/xxx.jpg）

安卓5.1.1的手机日志如下：
com.android.gallery E/UriImage: got exception decoding bitmap 
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.ParcelFileDescriptor android.content.ContentResolver.openFileDescriptor(android.net.Uri, java.lang.String)' on a null object reference
        at com.android.camera.Util.makeInputStream(Util.java:336)
        at com.android.camera.Util.makeBitmap(Util.java:307)
        at com.android.camera.Util.makeBitmap(Util.java:299)
        at com.android.camera.gallery.UriImage.fullSizeBitmap(UriImage.java:94)
        at com.android.camera.gallery.UriImage.fullSizeBitmap(UriImage.java:86)
        at com.android.camera.gallery.UriImage.thumbBitmap(UriImage.java:120)
        at com.android.camera.ImageGetter$ImageGetterRunnable.executeRequest(ImageGetter.java:173)
        at com.android.camera.ImageGetter$ImageGetterRunnable.run(ImageGetter.java:149)
        at java.lang.Thread.run(Thread.java:818)
01-31 07:50:51.423 8621-12100/com.android.gallery E/UriImage: got exception decoding bitmap 
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.ParcelFileDescriptor android.content.ContentResolver.openFileDescriptor(android.net.Uri, java.lang.String)' on a null object reference
        at com.android.camera.Util.makeInputStream(Util.java:336)
        at com.android.camera.Util.makeBitmap(Util.java:307)
        at com.android.camera.Util.makeBitmap(Util.java:299)
        at com.android.camera.gallery.UriImage.fullSizeBitmap(UriImage.java:94)
        at com.android.camera.ImageGetter$ImageGetterRunnable.executeRequest(ImageGetter.java:204)
        at com.android.camera.ImageGetter$ImageGetterRunnable.run(ImageGetter.java:149)
        at java.lang.Thread.run(Thread.java:818)

**Comment by crazecoder** [comment]
可能是因为intent是调用第三方app的关系，一般来说，第三方app是没有权限打开其他app内部存储目录的，主要还是得看被调用app的权限
