### ISSUE TITLE
App crashes on Android when flutter is reattached to engine

### ISSUE THREAD

**Issue by foreg** [crazecoder/open_file#152]
We use add-2-app flutter feature in our app. 

Steps to reproduce the crash: 
1. run an app
2. detach FlutterFragment from FlutterEngine
3. attach FlutterFragment to FlutterEngine

I think this crash could be solved by moving `this.flutterPluginBinding = null;` from onDetachedFromActivity to onDetachedFromEngine, as it was before version 3.2.1. 

Logs:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'io.flutter.plugin.common.BinaryMessenger io.flutter.embedding.engine.plugins.FlutterPlugin$FlutterPluginBinding.getBinaryMessenger()' on a null object reference
 at com.crazecoder.openfile.OpenFilePlugin.onAttachedToActivity(OpenFilePlugin.java:400)
 at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.attachToActivityInternal(FlutterEngineConnectionRegistry.java:362)
 at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.attachToActivity(FlutterEngineConnectionRegistry.java:344)
 at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:169)
 at io.flutter.embedding.android.FlutterFragment.onAttach(FlutterFragment.java:609)
 at androidx.fragment.app.Fragment.performAttach(Fragment.java:2574)
 at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:828)
 at androidx.fragment.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1197)
 at androidx.fragment.app.FragmentTransition.calculateFragments(FragmentTransition.java:1080)
 at androidx.fragment.app.FragmentTransition.startTransitions(FragmentTransition.java:119)
 at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1866)
 at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
 at androidx.fragment.app.FragmentManagerImpl.execSingleAction(FragmentManagerImpl.java:1696)
 at androidx.fragment.app.BackStackRecord.commitNow(BackStackRecord.java:293)
```

**Comment by liuGuiRong18** [comment]
This problem will come up again
