### ISSUE TITLE
Does not work with audio service plugin when trying to open application from splash

### ISSUE THREAD

**Issue by IlyaMax** [crazecoder/open_file#162]
Here is log
```
E/AndroidRuntime(32488): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'io.flutter.plugin.common.BinaryMessenger io.flutter.embedding.engine.plugins.FlutterPlugin$FlutterPluginBinding.getBinaryMessenger()' on a null object reference
E/AndroidRuntime(32488): 	at com.crazecoder.openfile.OpenFilePlugin.onAttachedToActivity(OpenFilePlugin.java:400)
E/AndroidRuntime(32488): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.attachToActivityInternal(FlutterEngineConnectionRegistry.java:362)
E/AndroidRuntime(32488): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.attachToActivity(FlutterEngineConnectionRegistry.java:344)
E/AndroidRuntime(32488): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:169)
E/AndroidRuntime(32488): 	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:409)
E/AndroidRuntime(32488): 	at android.app.Activity.performCreate(Activity.java:7955)
E/AndroidRuntime(32488): 	at android.app.Activity.performCreate(Activity.java:7944)
E/AndroidRuntime(32488): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
E/AndroidRuntime(32488): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3531)
```

**Comment by crazecoder** [comment]
```yaml
   open_file:
    git:
      url: https://github.com/crazecoder/open_file.git
```
Please let me know if it can solve the problem

**Comment by IlyaMax** [comment]
@crazecoder yes it solves

**Comment by IlyaMax** [comment]
@crazecoder could you please clarify when are you going to bump version of package?

**Comment by yanivshaked** [comment]
@crazecoder Any plans to release an official version with this fix?

**Comment by rajasuman09** [comment]
> 

It solved my issue too. But still it is not available in released plugin
