### ISSUE TITLE
Path not exists error

### ISSUE THREAD

**Issue by joanaggrey** [crazecoder/open_file#69]
Path not found after downloading the PDF file from the internet.

**Comment by crazecoder** [comment]
First, determine if the file has been downloaded, and second, determine if open is called after the download is complete

**Comment by braysonjohn148** [comment]
Am getting this error:

`java.lang.IllegalArgumentException: Failed to find configured root that contains /storage/emulated/0/Android/data/com.xcgx.droopy/files/Downloads/Dro.jpg`

Dows this open such directory:
/storage/emulated/0/Android/data/com.xcgx.droopy/files/

**Comment by crazecoder** [comment]
I will close this issue. If this problem still exists in the latest version, please inform me and I will reopen it

**Comment by braysonjohn148** [comment]
I checked this path it exists. But when i open the file i get this error: 
`/data/user/0/com.xcgx.droopy/app_flutter/MyNotes/20210602100141.pdf` Path am opening

Log i get:
```
E/MethodChannel#open_file(21557): Failed to handle method call
E/MethodChannel#open_file(21557): java.lang.IllegalArgumentException: Failed to find configured root that contains /data/data/com.xcgx.droopy/app_flutter/MyNotes/20210602100141.pdf
E/MethodChannel#open_file(21557): 	at androidx.core.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:744)
E/MethodChannel#open_file(21557): 	at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:418)
E/MethodChannel#open_file(21557): 	at com.crazecoder.openfile.OpenFilePlugin.startActivity(OpenFilePlugin.java:150)
E/MethodChannel#open_file(21557): 	at com.crazecoder.openfile.OpenFilePlugin.onMethodCall(OpenFilePlugin.java:106)
E/MethodChannel#open_file(21557): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#open_file(21557): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#open_file(21557): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/MethodChannel#open_file(21557): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#open_file(21557): 	at android.os.MessageQueue.next(MessageQueue.java:326)

```
