### ISSUE TITLE
Cannot open file from **getExternalStorageDirectory()** location.

### ISSUE THREAD

**Issue by braysonjohn148** [crazecoder/open_file#94]
java.lang.IllegalArgumentException: Failed to find configured root that contains /storage/emulated/0/Android/data/com.xcgx.droopy/files/Downloads/Dro.jpg

Dows this open such directory:
/storage/emulated/0/Android/data/com.xcgx.droopy/files

**Comment by braysonjohn148** [comment]
> java.lang.IllegalArgumentException: Failed to find configured root that contains /storage/emulated/0/Android/data/com.xcgx.droopy/files/Downloads/Dro.jpg
> 
> Dows this open such directory:
> /storage/emulated/0/Android/data/com.xcgx.droopy/files

Sorry i figure out in app/src/main/res/xml/filepath.xml should be:
<?xml version="1.0" encoding="utf-8"?>
<paths xmlns:android="http://schemas.android.com/apk/res/android">
    <cache-path name="image" path="/"/>

    <external-path name="external_files" path="." />
     <external-path name="files" path="Android/data/com.xcgx.droopy/" />

</paths>

**Comment by braysonjohn148** [comment]
OpenFile.open(). Cannot acces folder in getApplicationDocumentsDirectory() but can access file in /storage/emulated/0

**Comment by Iczp** [comment]
```
I/flutter ( 4721): │ ⛔ PlatformException(error, Failed to find configured root that contains /data/data/com.example.im/cache/file_picker/activity_mini.txt, null, java.lang.IllegalArgumentException: Failed to find configured root that contains /data/data/com.example.im/cache/file_picker/activity_mini.txt
I/flutter ( 4721): │ ⛔ 	at androidx.core.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:825)
I/flutter ( 4721): │ ⛔ 	at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:450)
I/flutter ( 4721): │ ⛔ 	at com.crazecoder.openfile.OpenFilePlugin.startActivity(OpenFilePlugin.java:150)
I/flutter ( 4721): │ ⛔ 	at com.crazecoder.openfile.OpenFilePlugin.onMethodCall(OpenFilePlugin.java:106)
I/flutter ( 4721): │ ⛔ 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
I/flutter ( 4721): │ ⛔ 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
I/flutter ( 4721): │ ⛔ 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
I/flutter ( 4721): │ ⛔ 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
I/flutter ( 4721): │ ⛔ 	at android.os.Handler.handleCallback(Handler.java:938)
I/flutter ( 4721): │ ⛔ 	at android.os.Handler.dispatchMessage(Handler.java:99)
I/flutter ( 4721): │ ⛔ 	at android.os.Looper.loop(Looper.java:236)
I/flutter ( 4721): │ ⛔ 	at android.app.ActivityThread.main(ActivityThread.java:8073)
I/flutter ( 4721): │ ⛔ 	at java.lang.reflect.Method.invoke(Native Method)
I/flutter ( 4721): │ ⛔ 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
I/flutter ( 4721): │ ⛔ 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
I/flutter ( 4721): │ ⛔ )
```

**Comment by renatolealdev** [comment]
I have the same problem!
